# Generated by Django 5.2.5 on 2026-06-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('is_popular', False), ('image_url__isnull', False), _connector='OR'), name='popular_category_requires_image'),
        ),
    ]
