# Generated by Django 5.2.5 on 2026-06-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_parent_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='popular_category_requires_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='category',
            name='delivered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category'),
        ),
    ]
